<?php

namespace AppBundle\Repository;

/**
 * BitstreamStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BitstreamStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
