<?php

namespace AppBundle\Repository;

/**
 * BitstreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BitstreamRepository extends \Doctrine\ORM\EntityRepository
{
}
