<?php

namespace AppBundle\Repository;

/**
 * BoardConfigRepository.php
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
