<?php

namespace AppBundle\Repository;

/**
 * ReservationDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationDataRepository extends \Doctrine\ORM\EntityRepository
{
}
